blockExoticSubdeps: true
preferFrozenLockfile: true
savePrefix: ""

minimumReleaseAge: 4320 # >=3 days
minimumReleaseAgeExclude:
  - "@pretty-cozy/oxlint-config@0.2.2"

trustPolicy: no-downgrade

ignoreWorkspaceRootCheck: true
packages:
  - ./
  - demos/*
